server:
  port: 9090

  servlet:
    context-path: /

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springbootwithmybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: html
    servlet:
      content-type: text/html
    enabled: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.athome.springbootwithmybatis.entity
#  configuration:
#    cache-enabled: true
#    lazy-loading-enabled: true #延迟加载两个配置
#    aggressive-lazy-loading: false #延迟加载两个配置
#    multiple-result-sets-enabled: true
#    use-column-label: true
#    use-generated-keys: false
#    auto-mapping-behavior: PARTIAL

#showSql
logging:
  level:
    com:
      athome:
        mapper: debug


